stages:
  collectDataStage:
    cmd: python3 src/collectData.py data/test.csv
    deps:
    - data/test.csv
    - src/collectData.py
    outs:
    - data/collected
  dataAnalysisStage:
    cmd: pythin3 src/src/dataAnalysis.py data/collected data/analysed
    deps:
    - data/collected
    - src/dataAnalysis.py
    outs:
    - data/analysed