input_features:
  - name: Datum
    type: date
    preprocessing:
      missing_value_strategy: fill_with_const
      fill_value: ''
      datetime_format: "YYYY-MM-DD"

  - name: Eroeffnung
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Tageshoch
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Tagestief
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Umsatz
    type: numerical
    preprocessing:
      normalization: zscore
  - name: RSI
    type: numerical
    preprocessing:
      normalization: zscore
  - name: SMA
    type: numerical
    preprocessing:
      normalization: zscore
  - name: EMA
    type: numerical
    preprocessing:
      normalization: zscore
  - name: DEMA
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Schluss
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Differenz
    type: numerical
    preprocessing:
      normalization: zscore

output_features:
  - name: "Schluss"
    type: numerical

training:
  batch_size: 64
  epochs: 100
  learning_rate: 0.0005
  optimizer:
    type: adam

preprocessing:
  split:
    type: datetime
    column: Datum
    probabilities: [0.7, 0.15, 0.15]

model:
  type: regressor
  layers:
    - fc_size: 256
      dropout: 0.3
    - fc_size: 256
      dropout: 0.3
    - fc_size: 128
      dropout: 0.3
