input_features:
  - name: Datum
    type: date
    preprocessing:
      missing_value_strategy: fill_with_const
      fill_value: ''
      datetime_format: "YYYY-MM-DD"

  - name: Eroeffnung
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Tageshoch
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Tagestief
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Umsatz
    type: numerical
    preprocessing:
      normalization: zscore
  - name: RSI
    type: numerical
    preprocessing:
      normalization: zscore
  - name: SMA
    type: numerical
    preprocessing:
      normalization: zscore
  - name: EMA
    type: numerical
    preprocessing:
      normalization: zscore
  - name: DEMA
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Schluss
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Differenz
    type: numerical
    preprocessing:
      normalization: zscore

output_features:
  - name: "Schluss naechster Tag"
    type: numerical

training:
  batch_size: 64  # Erhöht für stabileres Training
  epochs: 100  # Mehr Epochen für längeres Training
  learning_rate: 0.0005  # Anpassung der Lernrate
  optimizer:
    type: adam

preprocessing:
  split:
    type: datetime
    column: Datum
    probabilities: [0.7, 0.15, 0.15]

model:
  type: deep_lstm
  num_layers: 4  # Erhöht für eine tiefere Modellarchitektur
  num_hidden_units: 256  # Erhöht für größere Kapazität
  dropout: 0.3  # Erhöht, um Overfitting zu reduzieren
  recurrent_dropout: 0.3  # Erhöht, um Overfitting zu reduzieren
