input_features:
  - name: Datum
    type: date
  - name: Eroeffnung
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Tageshoch
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Tagestief
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Umsatz
    type: numerical
    preprocessing:
      normalization: zscore
  - name: RSI
    type: numerical
    preprocessing:
      normalization: zscore
  - name: SMA
    type: numerical
    preprocessing:
      normalization: zscore
  - name: EMA
    type: numerical
    preprocessing:
      normalization: zscore
  - name: DEMA
    type: numerical
    preprocessing:
      normalization: zscore
  - name: Schluss
    type: numerical
    preprocessing:
      normalization: zscore

output_features:
  - name: "Schlusskurs nächster Tag"
    type: numerical

training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  optimizer:
    type: adam

preprocessing:
  split:
    type: stratify
    probabilities: [0.7, 0.15, 0.15]

model:
  type: deep_lstm
  num_layers: 2
  num_hidden_units: 128
  dropout: 0.2
  recurrent_dropout: 0.2
