artifact_uri: file://C:\Users\simon\PycharmProjects\Docker_LudwigMLCore\mlflow_tracking/0/7e7dcd1c88724584a1d206e34dec4727/artifacts
end_time: 1703077941176
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7e7dcd1c88724584a1d206e34dec4727
run_name: capable-auk-759
run_uuid: 7e7dcd1c88724584a1d206e34dec4727
source_name: ''
source_type: 4
source_version: ''
start_time: 1703077940883
status: 3
tags: []
user_id: simon
