services:

  dagster-dagit:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}   
    ports:
      - 3078:3000
    
  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    command: "dagster-daemon run"
    environment:
      - PGPASS=demopass
      - PGUID=postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker:/bin/docker

  dagster-postgres:
    image: postgres:13.3
    ports:
      - 4078:5432
    environment:
      - POSTGRES_PASSWORD=demopass
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
volumes:
  dagster-postgres:
    driver: local